news/urls.py
from django.urls import path
from .views import (BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView,
                    BlogDeleteView, News, ContactsView,)

urlpatterns = [
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('', BlogListView.as_view(), name='home'),
    path('news/', News.as_view(), name='news'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
]

sadik_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('bashkaru/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('news.urls')),
    path('', include('table.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

table/models.py
from django.db import models
from django.urls import reverse
from _datetime import datetime


class Group(models.Model):
    group_name = models.CharField(max_length=20, verbose_name='Тайпанын аты')
    group_year_from = models.PositiveIntegerField(verbose_name='Жылдан баштап')
    group_year_to = models.PositiveIntegerField(verbose_name='Жылга чейин')
    about_text = models.CharField(max_length=255, verbose_name='Тайпана жөнүндө маалымат')
    group_reg = models.IntegerField(verbose_name='Окуучулардын саны')
    group_teachers = models.CharField(max_length=20, verbose_name='Мугалимдердин саны')
    group_img = models.ImageField(upload_to='images/', default='images/def.jpg', blank=True,
                                  verbose_name='Тайпанын cүрөтү')

    def __str__(self):
        return f'{self.group_name}'


class Queue(models.Model):
    CHILD_GENDER = [
        ('Erkek', 'Уул'),
        ('Kyz', 'Кыз')
    ]

    child_name = models.CharField(max_length=200,
                                  verbose_name='Баланын Аты-Жөнү')
    child_gender = models.CharField(max_length=10, choices=CHILD_GENDER,
                                    verbose_name='Баланын жыныс')
    child_birthday = models.DateField(verbose_name='Баланын Туулган күнү')
    birth_certificate = models.CharField(max_length=15,
                                         verbose_name='Туулгандыгы туралуу Күболүктүн номери')
    custom_given_certificate = models.CharField(max_length=15,
                                                verbose_name='Күбөлүктүү берген Орган')
    certificate_given_date = models.DateField(verbose_name='Күбөлүктү берген күнү')
    child_address = models.CharField(max_length=255, verbose_name='Дарек')
    parent_name = models.CharField(max_length=255, verbose_name='Ата-Энесинин Аты-Жөнү')
    parent_phone = models.CharField(max_length=20, verbose_name='Телефону')
    registration_date = models.DateTimeField(default=datetime.now,
                                             verbose_name='Арызы катталган күнү')
    choice_group = models.ForeignKey(Group, related_name='groups', on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return '{}{}{}'.format(self.child_name, self.child_birthday,
                               self.custom_given_certificate, )

    def get_absolute_url(self):
        return reverse('queue', args=[str(self.id)])


class Name(models.Model):
    garden_name = models.CharField(max_length=30, verbose_name="Бала бакчанын аты")
    garden_address = models.CharField(max_length=50, verbose_name="Бала бакчанын дареги")
    garden_phone = models.CharField(max_length=20, verbose_name="Бала бакчанын телефону")
    garden_email = models.CharField(max_length=20, verbose_name="Бала бакчанын почтасы")
    garden_info = models.TextField(verbose_name="Бала бакча жөнүндө маалымат")
    garden_start = models.CharField(max_length=20, verbose_name="Бала бакчанын ачылуу убакыты")
    garden_end = models.CharField(max_length=20, verbose_name="Бала бакчанын жабылуу убакыты")
    garden_map_lat = models.CharField(max_length=30, verbose_name="Широта")
    garden_map_lon = models.CharField(max_length=30, verbose_name="Долгота")

    def get_absolute_url(self):
        return reverse('name', args=[str(self.id)])

    def __str__(self):
        return '{}'.format(self.garden_name)

templates/queue/queue.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Begin page name -->
    <section class="page-name mb-xs-30 mb-md-30 mb-lg-60">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1 class="text-center">Электрондук кезек</h1>
                </div>
            </div>
        </div>
        <div class="layer-background lazy" data-src="{% static 'img/slider.png' %}"></div>
        <img src="{% static 'img/lazy.png' %}" class="page-name-img lazy" data-src="{% static 'img/cloud.png' %}"
             alt="Img">
    </section>
    <!-- End page name -->
    <main class="main-container">
        <!-- Begin contacts -->
        <section class="contact-container pt-60 pb-60 pt-xs-30 pb-xs-30 pt-md-60 pb-md-60 r-cloud">
            <div class="container">
                <div class="row">
                    <div class="section-header on-scroll">
                        <p class="h-sub">«{{ top_name.garden_name }}»МЧББМсинин кезекте турган балдардын тизмеси.</p>
                    </div>
                    <!--Table-->
                    <div class="col-md-12 col-xs-12">
                        <table class="table table-striped">
                            <!--Table head-->
                            <thead>
                            <tr>
                                <th style="width: 50px;">№</th>
                                <th>Аты-жөнү</th>
                                <th>Туулган-күнү</th>
                                <th>Арыздын катталган күнү</th>
                                {% if user.is_authenticated %}
                                    <th>Туулгандыгы туралуу Күбөлүк</th>
                                    <th>Дарек</th>
                                    <th>Ата-Эне</th>
                                    <th>Телефон</th>
                                    <th>Тайпа</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <!--Table head-->

                            <!--Table body-->
                            <tbody>
                            {% for post in object_list %}
                                {% if post.choice_group.id == None %}
                                    <tr>
                                        <th class="counterCell"></th>
                                        <td>{{ post.child_name }}</td>
                                        <td>{{ post.child_birthday }}</td>
                                        <td>{{ post.registration_date }}</td>
                                        {% if user.is_authenticated %}
                                            <td>{{ post.birth_certificate }}</td>
                                            <td>{{ post.child_address }}</td>
                                            <td>{{ post.parent_name }}</td>
                                            <td>{{ post.parent_phone }}</td>
                                            <td><a href="{% url 'queue_update' post.id %}">Ɵзгөртүү</a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                            <!--Table body-->
                        </table>
                        <!--Table-->
                    </div>
                </div>
            </div>
        </section>
        <!-- End contacts -->
    </main>
{% endblock content %}

templates/queue/queue_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Begin page name -->
    <section class="page-name mb-xs-30 mb-md-30 mb-lg-60">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1 class="text-center">Аккаунтту өчүрүү</h1>
                </div>
            </div>
        </div>
        <div class="layer-background lazy" data-src="{% static 'img/slider.png' %}"></div>
        <img src="{% static 'img/lazy.png' %}" class="page-name-img lazy" data-src="{% static 'img/cloud.png' %}"
             alt="Img">
    </section>
    <!-- End page name -->
   <div class="container">
    <form action="" method="post">{% csrf_token %}
        <p><h2>Сиз, "{{ queue.child_name }}ти" тизмеден өчүргүңүз келеби?</h2>
        <button type="submit" value="Тастыктоо" class="btn btn-danger">Тастыктоо</button>
    </form>
   </div>
{% endblock content %}

templates/queue/queue_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="post-entry">
        <h2>{{ queue.child_name }}</h2>
        <p>{{ queue.child_birthday }}</p>
    </div>
    {% if user.is_authenticated %}
    <button class="btn btn-success"><a href="{% url 'queue_update' queue.pk %}" style="color: white">Жаңылыкты өзгөртүү</a></button>
    <button class="btn btn-danger"><a href="{% url 'queue_delete' queue.pk %}" style="color: white">Жаңылыкты өчүрүү</a></button>
    {% endif %}
{% endblock content %}

templates/queue/queue_new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Begin page name -->
    <section class="page-name mb-xs-30 mb-md-30 mb-lg-60">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1 class="text-center">Электрондук каттоого арыз берүү</h1>
                </div>
            </div>
        </div>
        <div class="layer-background lazy" data-src="{% static 'img/slider.png' %}"></div>
        <img src="{% static 'img/lazy.png' %}" class="page-name-img lazy" data-src="{% static 'img/cloud.png' %}"
             alt="Img">
    </section>
    <!-- End page name -->
    <div class="container">
        <div class="col-md-4 col-xs-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p><label for="id_child_name">Баланын Аты-Жөнү:</label> <input type="text" name="child_name"
                                                                                   maxlength="200" required=""
                                                                                   id="id_child_name"></p>
                    <p><label for="id_child_gender">Баланын жыныс:</label> <select name="child_gender" required=""
                                                                                   id="id_child_gender">
                        <option value="" selected="">---------</option>

                        <option value="Erkek">Уул</option>

                        <option value="Kyz">Кыз</option>

                    </select></p>

                    <p><label for="id_child_birthday">Баланын Туулган күнү:</label>
                        <input type="date"
                               name="child_birthday"
                               required=""
                               id="id_child_birthday"></p>


                    <p><label for="id_birth_certificate">Туулгандыгы туралуу Күболүктүн номери:</label> <input
                            type="text" name="birth_certificate" maxlength="15" required="" id="id_birth_certificate">
                    </p>
                    <p><label for="id_custom_given_certificate">Күбөлүктүү берген Орган:</label> <input type="text"
                                                                                                        name="custom_given_certificate"
                                                                                                        maxlength="15"
                                                                                                        required=""
                                                                                                        id="id_custom_given_certificate">
                    </p>
                    <p><label for="id_certificate_given_date">Күбөлүктү берген күнү:</label> <input type="date"
                                                                                                    name="certificate_given_date"
                                                                                                    required=""
                                                                                                    id="id_certificate_given_date">
                    </p>
                    <p><label for="id_child_address">Дарек:</label> <input type="text" name="child_address"
                                                                           maxlength="255" required=""
                                                                           id="id_child_address"></p>
                    <p><label for="id_parent_name">Ата-Энесинин Аты-Жөнү:</label> <input type="text" name="parent_name"
                                                                                         maxlength="255" required=""
                                                                                         id="id_parent_name"></p>
                    <p><label for="id_parent_phone">Телефону:</label> <input type="text" name="parent_phone"
                                                                             maxlength="20" required=""
                                                                             id="id_parent_phone"></p>
                    <button class="btn btn-info" type="submit" value="Сактоо">Сактоо</button>
                </form>
            </form>
        </div>
    </div>

<script src="{% static 'vendor/js/main.js' %}"></script>
{% endblock content %}

templates/queue/queue_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Begin page name -->
    <section class="page-name mb-xs-30 mb-md-30 mb-lg-60">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1 class="text-center">Аккаунту өзгөртүү</h1>
                </div>
            </div>
        </div>
        <div class="layer-background lazy" data-src="{% static 'img/slider.png' %}"></div>
        <img src="{% static 'img/lazy.png' %}" class="page-name-img lazy" data-src="{% static 'img/cloud.png' %}"
             alt="Img">

    </section>
    <!-- End page name -->
    <div class="container">
        <div class="row">
            {% if queue.choice_group == '0' %}
            {% else %}
            <div class="col-md-12">
                <h2>{{ queue.child_name }}</h2>
                    <button class="btn btn-danger">
                        <a href="{% url 'queue_delete' queue.pk %}" style="color: white">Тизмеден
                        өчүрүү</a></button>
                <hr>
            </div>
            {% endif %}
            <div class="col-md-3 col-xs-12">
                <p>Башка тайпага которуу</p>
                <form action="" method="post">
                    {% csrf_token %}
                   {{ form.as_p }}
                    <button type="submit" value="Жаңылоо" class="btn btn-info">Жаңылоо</button>
                </form>
            </div>

        </div>
    </div>
{% endblock content %}